#!/usr/bin/env bash
# Expand urdf/ava.urdf.xacro into a plain urdf/ava.urdf and validate it.
#
# ava.urdf is GENERATED and committed so that tools which cannot run xacro
# (the web dashboard, MuJoCo, other viewers) can read the robot. Never edit it
# by hand: change the xacro files and re-run this script.
#
# Usage (from anywhere, after sourcing ROS and the workspace):
#   source /opt/ros/jazzy/setup.bash
#   source ros2_ws/install/setup.bash
#   ros2_ws/src/ava_description/scripts/generate_urdf.sh
set -euo pipefail

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IN="${PKG_DIR}/urdf/ava.urdf.xacro"
OUT="${PKG_DIR}/urdf/ava.urdf"
TMP="$(mktemp)"
trap 'rm -f "${TMP}"' EXIT

for tool in xacro check_urdf; do
  command -v "${tool}" >/dev/null || { echo "ERROR: '${tool}' not found - source /opt/ros/jazzy/setup.bash" >&2; exit 1; }
done
# $(find ava_description) inside the xacro needs the package on the ament index.
ros2 pkg prefix ava_description >/dev/null 2>&1 || {
  echo "ERROR: ava_description not found - build ros2_ws and source install/setup.bash" >&2; exit 1; }

# mock_components: the one hardware type with no machine-specific values (serial port etc.)
xacro "${IN}" ros2_control_hardware_type:=mock_components > "${TMP}"

if ! check_urdf "${TMP}" > /dev/null; then
  echo "ERROR: check_urdf rejected the expanded URDF - ${OUT} NOT updated" >&2
  check_urdf "${TMP}" >&2 || true
  exit 1
fi

{
  echo '<?xml version="1.0"?>'
  echo '<!-- GENERATED by scripts/generate_urdf.sh from urdf/ava.urdf.xacro - DO NOT EDIT -->'
  # drop xacro's own XML declaration and its banner (it embeds this machine's absolute path)
  sed -e '1{/^<?xml/d}' -e '/^<!-- [=|]/d' "${TMP}"
} > "${OUT}"

echo "OK: wrote ${OUT} (check_urdf passed)"
